app = "tete-fastapi"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  # HTTPS only
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/"
    protocol = "http"

  [services.concurrency]
    type = "connections"
    soft_limit = 40
    hard_limit = 50
