# fly.toml
app = "tete-fastapi"         # change to your app name
primary_region = "lhr"       # pick nearby region
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  # nothing hard-coded; set OPENAI_API_KEY as a secret

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

  # Optional: let a few concurrent connections queue instead of 502’s under load
  [services.concurrency]
    hard_limit = 50
    soft_limit = 40
    type = "connections"
